=== Adri01023/1DAM/Lenguaje de Marcas/prueba1.dtd
<!ELEMENT agenda (persona*)>
<!-- ? = 0 o 1 vez, * 0 o N veces, + 1 o N veces | or-->
<!ELEMENT persona (nombre,apellido+,telefono?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono fijo (true|false) #REQUIRED trabajo (true|false) #IMPLIED>
<!-- <!ELEMENT telefono ((fijo,movil?) | (fijo?,movil))>
<!ELEMENT fijo (#PCDATA)>
<!ELEMENT movil (#PCDATA)> -->

=== Adri01023/1DAM/Lenguaje de Marcas/prueba1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE  agenda SYSTEM "prueba1.dtd">
<agenda>
<persona>
<nombre>Pepe</nombre>
<apellido>Garcia</apellido>
<apellido>Morales</apellido>
<telefono fijo="true">91124521</telefono>
</persona>
<persona>
<nombre>Macarena</nombre>
<apellido>Olona</apellido>
<telefono fijo="false" trabajo="false">624578454</telefono>
</persona>
</agenda>
